### ISSUE TITLE
Linear gauge graph always starts at zero

### ISSUE THREAD

**Issue by aldweb** [smolbun/linear-gauge-card#2]
Not all sensors start at 0. For example, CO2 starts at ~400 ppm, sea pressure starts at ~950 hPa, temperature might go below 0°C.
It could be great to have a starting value different from zero, that could be like (example for CO2):
```
segments:
  - start: 400
  - until: 800
    color: '#43A047'
  - until: 1200
    color: '#FFC300'
  - until: 2000
    color: '#DB4437'
```

Cheers,
aldweb

**Comment by smolbun** [comment]
Are you looking for something like this?

![Image](https://github.com/user-attachments/assets/cfc3261b-db1d-4af5-813a-b6b87cd857a4)

**Comment by aldweb** [comment]
That's exactly what I am looking for :-)
Be careful that with white background, the numbers below remain white and the read value of the sensor is very pale:
![Image](https://github.com/user-attachments/assets/ec995d20-acca-4712-9b14-80697c2661b4)

And, uptimately, I would maybe love even more if I was able to reproduce something similar to my current home made development (in php):
![Image](https://github.com/user-attachments/assets/c77d723f-294f-427b-af39-d57fdfc9f23e)
As you can see, the various sensors are grouped in a small space, color coding indicates if you overpass or not a limit.

Cheers,
aldweb

**Comment by smolbun** [comment]
Thanks for the feedback, I've implemented the feature [here](https://github.com/smolbun/linear-gauge-card/commit/425ff2d17a23f1f02e3a773174e847bd40ce59b5).
You may set the color of the text like this:
```
dataLabelTextColor: black
gridLabelTextColor: black
```
As for the graph you made, it looks great; I'll consider making another card if I have the time. Do let me know if there are any other issues, or else you may close the issue once you've tested it out. Remember to clear your cache when reloading :)

**Comment by aldweb** [comment]
Wondeful! Thank you so much.

![Image](https://github.com/user-attachments/assets/5cbd7d85-e888-44c0-87c8-c256bf397371)

**Comment by aldweb** [comment]
Sorry, I closed too fast...
Here is a series of sensors gauges:
![Image](https://github.com/user-attachments/assets/6afdf6d8-6556-44f8-aff7-e307b225d13f)
The issue is with the barometer sensor, for which gauge settings are:
```
type: custom:linear-gauge-card
entity: sensor.wenv_1_bme680_seapressure
name: Barometer (hPa)
dataLabelTextColor: black
gridLabelTextColor: black
segments:
  - until: 1000
    start: 950
    color: "#DB4437"
  - until: 1020
    color: "#FFC300"
  - until: 1070
    color: "#43A047"
```
The red bar is clearly oversized...
All other sensors render correctly.
