### ISSUE TITLE
Incorrect bar width calculation

### ISSUE THREAD

**Issue by smolbun** [smolbun/linear-gauge-card#3]
Issue described [here](https://github.com/smolbun/linear-gauge-card/issues/2#issuecomment-2679822097).

**Comment by smolbun** [comment]
Hi @aldweb, try to change this line:
`const max = this.config.segments[this.config.segments.length - 1].until;`
to
`const max = this.config.segments[this.config.segments.length - 1].until + this.config.start;`

![Image](https://github.com/user-attachments/assets/07364e85-2b13-46e2-a55c-0c3ad6a1e8b2)

Let me know if the output is expected.

**Comment by smolbun** [comment]
@aldweb, please try [this](https://github.com/smolbun/linear-gauge-card/blob/8c65afebbba9536e9944d47bbc249e077f5f4800/linear-gauge-card.js).
```
type: custom:linear-gauge-card
entity: sensor.wenv_1_bme680_seapressure
name: Barometer (hPa)
dataLabelTextColor: black
gridLabelTextColor: black
start: 950
startVisibility: visible
segments:
  - until: 1000
    color: "#DB4437"
  - until: 1020
    color: "#FFC300"
  - until: 1070
    color: "#43A047"
```
